import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const root = new URL('../Frontend/static/js/', import.meta.url);
const moduleURL = source => 'data:text/javascript;base64,' + Buffer.from(source).toString('base64');
const linksURL = moduleURL(readFileSync(new URL('place-links.js', root), 'utf8'));
const {mapUrl, placeSegments, renderPlaceText} = await import(linksURL);
const itinerarySource = readFileSync(new URL('itinerary.js', root), 'utf8').replace('./place-links.js?v=improvements-1', linksURL);
const {splitDays} = await import(moduleURL(itinerarySource));
const kyoto={name:'City Museum',location:'Kyoto, Japan'};
const paris={name:'City Museum',location:'Paris, France'};
assert.equal(new URL(mapUrl(kyoto)).searchParams.get('query'),'City Museum, Kyoto, Japan');
assert.notEqual(mapUrl(kyoto),mapUrl(paris));
assert.equal(mapUrl({name:' '}),null);
assert.equal(placeSegments('City Museums',[kyoto]).some(s=>s.url),false);
assert.equal(placeSegments('City Museum',[kyoto,paris]).some(s=>s.url),false);
assert.equal(placeSegments('City Museum Annex',[kyoto,{name:'City Museum Annex'}])[0].text,'City Museum Annex');
const blocks=splitDays('Welcome!\nDay 1: Gardens\nMorning: City Museum\nDay 2: Art\nAfternoon: Gallery');
assert.equal(blocks.length,3);
assert.equal(blocks[2].title,'Day 2: Art');
assert.equal(blocks.map(b=>[b.title,...b.lines].filter(Boolean).join('\n')).join('\n'),'Welcome!\nDay 1: Gardens\nMorning: City Museum\nDay 2: Art\nAfternoon: Gallery');
assert.equal(splitDays('Just a normal reply.')[0].title,'');
// A minimal DOM verifies rendering creates text nodes, never HTML from the model.
globalThis.document={createTextNode:text=>({text}),createElement:tag=>({tag})};
const children=[];
renderPlaceText({append:child=>children.push(child)},'<script>alert(1)</script> City Museum',[kyoto]);
assert.equal(children[0].text,'<script>alert(1)</script> ');
assert.equal(children[1].tag,'a');
assert.equal(children[1].href,mapUrl(kyoto));
assert.equal(children[1].rel,'noopener noreferrer');
console.log('Frontend checks passed: name/context links, ambiguity, day sections, safe text rendering.');
